# Server config file. It is read when the server starts. For front-end macros, see 'frontend/tokens.m4'.

# Directory where "media" folder will reside, into which user-submitted media is stored. A relative path can be used.
media_path = .

# Serves http://localhost:8300 by default. Change this if running multiple Mediaboard instances.
port = 8300

# Number of async threads. Values greater than 1 should be used for testing only.
threads = 1

# Name of the postgresql database to connect to. Cannot contain spaces.
database = fuze_mediaboard

# Values other than "localhost" are untested. Beware.
database_host = localhost

# The port which the database serves.
database_port = 5432

# Whether Fuze Mediaboard manages the database locally in a separate cluster.
# If true, the cluster will automatically be created on first run, and will spin up each time the server is started.
# Note: this may not work depending on your OS. It is confirmed working on FreeBSD.
manage_cluster = false
