# Server config file. It is read when the server starts. For front-end macros, see 'frontend/tokens.m4'.

# Directory where "media" folder will reside, into which user-submitted media is stored. A relative path can be used.
media_path = .

# Serves http://localhost:8300 by default. Change this if running multiple Mediaboard instances.
port = 8300

# Number of async threads. Values greater than 1 should be used for testing only.
threads = 1

# Which database engine to use. sqlite stores all the data in one file, whilst postgres is more advanced.
database_engine = sqlite
# database_engine = postgres

# Database connection target. Only used when database_engine = postgres
# See: https://www.postgresql.org/docs/current/ecpg-connect.html#ECPG-CONNECTING
postgresql_target = fuze_mediaboard@localhost:5432
