# Server config file. It is read when the server starts.

# Directory in which user-submitted media will be stored. A relative path can be used.
# media_directory = media

# Serves http://localhost:8300 by default. Change this if running multiple Mediaboard instances.
server_port = 8300

# Number of async threads. Values greater than 1 should be used for testing only.
threads = 1

# Limit of user-uploaded file size, in MB. Apply a reasonable limit to prevent abuse.
# file_size_limit_mb = 25

# favicon_url = https://fuze.page/favicon.ico
# site_name = Fuze Mediaboard
# show_watermarks = false

# Format must be supported by ImageMagick.
# Ignored when WITH_MAGICK=OFF
# Please note that any change in this setting will not apply to existing thumbnails - those will have to be converted manually.
# thumbnail_file_extension = jpg
# thumbnail_size = 150

# strip_metadata = true
# Requires the respective formats to be installed in the instance of ImageMagick used - Use `magick -list format` to see if they are supported.
# avif_thumbnails = true
# heic_thumbnails = true
# svg_thumbnails = true
# webp_thumbnails = true
### ffmpeg must be installed to make thumbnails from video files
# mp4_thumbnails = true
# webm_thumbnails = true
# Converts HEIC images to JPG on upload.
# convert_heic_to_jpg = true

# Only used when FUZEDBI_SQLITE is set
# sqlite_database_file = database/sqlite_data.db

# Database connection target. Only used when FUZEDBI_POSTGRES is set
# See: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
# postgresql_use_uri is experimental
postgresql_use_uri = false
# postgresql_uri = mediaboard_server@localhost:5432/fuze_mediaboard
postgresql_host = localhost
postgresql_port = 5432
postgresql_user = mediaboard_server
postgresql_database_name = fuze_mediaboard
