CREATE TABLE _owner(account_id INTEGER NOT NULL);
CREATE TABLE _sequences(account_id INTEGER, permission_group_id INTEGER);
INSERT INTO _sequences VALUES (0,0);
CREATE TABLE account(id INTEGER PRIMARY KEY, username TEXT, password_hash_hash_base64 TEXT, intermediate_salt_base64 TEXT);
CREATE TABLE session(id_base64 TEXT PRIMARY KEY, account_id INTEGER, created_at INTEGER);
CREATE TABLE permission_group(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE permission_group_heirarchy(rank INTEGER, permission_group INTEGER);
CREATE TABLE permission_group_account(group_id INTEGER, account_id INTEGER);
CREATE TABLE permission_collection(id INTEGER PRIMARY KEY, permission_object_id INTEGER, account_id INTEGER, permission_group_id INTEGER);
CREATE TABLE permission_setting(id INTEGER PRIMARY KEY, permission_collection_id INTEGER, permission_number INTEGER, setting INTEGER);
