CREATE TABLE _info(version TEXT);
CREATE TABLE _owner(account_id INTEGER NOT NULL);
CREATE TABLE _sequences(account_id INTEGER, board_id INTEGER, client_id INTEGER, message_id INTEGER, permission_collection_id INTEGER, permission_group_id INTEGER, permission_object_id INTEGER, permission_setting_id INTEGER, thread_id INTEGER);
INSERT INTO _sequences VALUES (0, 0, 0, 3, 3, 2, 0, 0);
CREATE TABLE account(id INTEGER PRIMARY KEY, username TEXT, password_hash_hash_base64 TEXT, intermediate_salt_base64 TEXT);
CREATE TABLE client(id INTEGER PRIMARY KEY, account_id INTEGER);
CREATE TABLE permission_collection(id INTEGER PRIMARY KEY, permission_object_id INTEGER, account_id INTEGER, permission_group_id INTEGER);
CREATE TABLE permission_group(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE permission_group_account(permission_group_id INTEGER, account_id INTEGER);
CREATE TABLE permission_group_heirarchy(rank INTEGER, permission_group_id INTEGER);
CREATE TABLE permission_setting(id INTEGER PRIMARY KEY, permission_collection_id INTEGER, permission_number INTEGER, setting INTEGER);
CREATE TABLE session(client_id INTEGER, key TEXT, created_at INTEGER);
CREATE TABLE message(id INTEGER PRIMARY KEY, thread_id INTEGER, id_in_thread INTEGER, board_id INTEGER, author_client_id INTEGER, author_username TEXT, created_at INTEGER, content TEXT, deleted BOOLEAN DEFAULT FALSE);
CREATE TABLE message_file(message_id INTEGER, file_name TEXT, width INTEGER, height INTEGER, thumbnail_file_extension TEXT);
CREATE TABLE thread(id INTEGER PRIMARY KEY, deleted BOOLEAN DEFAULT FALSE, board_id INTEGER, id_in_board INTEGER, message_id_seq INTEGER DEFAULT 0, permission_object_id INTEGER);
CREATE TABLE board(id INTEGER PRIMARY KEY, slug TEXT, title TEXT, thread_id_seq INTEGER DEFAULT 0, permission_object_id INTEGER, deleted BOOLEAN DEFAULT FALSE);
INSERT INTO board(id, slug, title, permission_object_id) VALUES (0, 'board', 'Board', 1);
INSERT INTO permission_group(id, name) VALUES (0, 'Owner');
INSERT INTO permission_group(id, name) VALUES (1, 'Accounts');
INSERT INTO permission_group(id, name) VALUES (2, 'Public');
INSERT INTO permission_group_heirarchy(rank, permission_group_id) VALUES (0, 0);
INSERT INTO permission_group_heirarchy(rank, permission_group_id) VALUES (1, 1);
INSERT INTO permission_group_heirarchy(rank, permission_group_id) VALUES (2, 2);
