INSERT INTO permission_group(id, name) VALUES (0, 'Administrators');
INSERT INTO permission_group(id, name) VALUES (1, 'Users');
INSERT INTO permission_group(id, name) VALUES (2, 'Public');
INSERT INTO permission_group_heirarchy(rank, permission_group) VALUES (0, 0);
INSERT INTO permission_group_heirarchy(rank, permission_group) VALUES (1, 1);
INSERT INTO permission_group_heirarchy(rank, permission_group) VALUES (2, 2);
INSERT INTO permission_collection(id, permission_object_id, permission_group_id) VALUES (0, 0, 0);
INSERT INTO permission_setting(id, permission_collection_id, permission_number, setting) VALUES (0, 0, 0, 2);
INSERT INTO permission_setting(id, permission_collection_id, permission_number, setting) VALUES (1, 0, 1, 2);
INSERT INTO permission_setting(id, permission_collection_id, permission_number, setting) VALUES (2, 0, 2, 2);
INSERT INTO permission_setting(id, permission_collection_id, permission_number, setting) VALUES (3, 0, 3, 2);
