#include "post.hpp"
#include "db_interface.h"
#include "DatabaseConnection.hpp"
#include <string>
#include <iostream>
#include <ctime>
#include <cstring>

// Cache post from database interface struct
Post::Post(struct db_post_struct* post_struct, DatabaseConnection* db)
		: db(db) {
	// std::cout << "createFromStruct ID: " << post_struct->id << std::endl;
	this->id = post_struct->id;
	this->thread_id = post_struct->thread_id;
	this->id_in_thread = post_struct->id_in_thread;
	this->name = post_struct->name;
	this->content = post_struct->content;
	this->upload_timestamp = post_struct->upload_timestamp;
	this->files_i = post_struct->number_of_files;
	for (short file_i = 0; file_i < this->files_i; file_i++) {
		// this->files[file_i] = post_struct->files[file_i];
		strcpy(this->files[file_i], post_struct->files[file_i]);
	}
	this->deleted = post_struct->deleted;
	this->key = post_struct->key;

	this->post_as_json["id"] = this->id;
	this->post_as_json["thread_id"] = this->thread_id;
	this->post_as_json["id_in_thread"] = this->id_in_thread;
	this->post_as_json["name"] = this->name;
	this->post_as_json["content"] = this->content;
	this->post_as_json["upload_timestamp"] = this->upload_timestamp;
	this->post_as_json["files"] = json::array();
	for (short file_i = 0; file_i < this->files_i; file_i++) {
		this->post_as_json["files"].push_back(this->files[file_i]);
	}
	// this->post_as_json["key"] = this->key;
}

// Save post when JSON is received
Post::Post(json post_json, DatabaseConnection* db)
		: db(db) {
	this->post_as_json = post_json;
	this->post_as_json["type"] = "post";

	this->id_in_thread = post_json["id_in_thread"].template get<int>();
	this->thread_id = post_json["thread_id"].template get<int>();

	// User input checking is done on front-end, so it's not high priority to return an http error when username or content is empty/too long.
	this->name = post_json["name"].template get<std::string>();
	if (this->name == "") {
		this->name = "Anonymous"; // Blank username becoming Anonymous is intended behaviour
		this->post_as_json["name"] = this->name;
	}
	else if (this->name.length() > POST_MAX_NAME) {
		this->name = "Bad Username"; 
		this->post_as_json["name"] = this->name;
	}
	this->content = post_json["content"].template get<std::string>();
	// if (this->content == "") {
	// 	this->content = "I'm speechless."; // Post looks ugly with empty content.
	// 	this->post_as_json["content"] = this->content;
	// }
	if (this->content.length() > POST_MAX_CONTENT) {
		this->content = "I have much to say.";
		this->post_as_json["content"] = this->content;
	}

	// A random key is generated by the index.html and is sent with the post.
	// It is a rudimentary way of verifying the author, used in the delete feature.
	this->key = post_json["key"].template get<std::string>();
	if (this->key.length() > KEY_LENGTH) {
		this->key = this->key.substr(0, KEY_LENGTH);
	}
	this->post_as_json.erase("key"); // Don't include key in the JSON for everyone to see.

	// vector should be replaced with an array. that requires editing the json template
	std::vector<std::string> file_vector = post_json["files"].template get<std::vector<std::string>>();
	std::vector<std::string>::iterator it = file_vector.begin();
	this->files_i = 0;
	while (it != file_vector.end()) {
		if ((*it).length() <= POST_MAX_FILE_NAME_WITH_UUID) {
			strcpy(this->files[files_i++], (*it).c_str());
		}
		else
			std::cerr << "File name too long to save to database. Length: " << (*it).length() << std::endl;
		it++;
	}
	// ID and timestamp are not initially known
	this->upload_timestamp = std::time(nullptr);
	this->post_as_json["upload_timestamp"] = this->upload_timestamp;

	this->id = db_store_post(this->thread_id, this->id_in_thread, this->name.c_str(), this->upload_timestamp, this->content.c_str(), this->files, this->files_i, this->key.c_str());
	this->post_as_json["id"] = this->id;

	// New posts are not in a deleted state
	this->deleted = false;
	// Moderators will be able to view deleted messages
	// this->post_as_json["deleted"] = false;
}

std::string Post::dumpPost() const {
	return this->post_as_json.dump();
}

void Post::markAsDeleted() {
	this->deleted = true;
	db_mark_post_as_deleted(this->id);
}
